#!/usr/bin/env bash
# =============================================================================
# Fix-NodeTLS.sh — Global NODE_TLS fix for Gemini CLI
# Compatible with: Microsoft Intune for Linux / Canonical Landscape
#
# Problem: The Gemini CLI (Node.js) fails to authenticate with the error:
#   "Premature close" or "Failed to sign in" because the corporate network
#   performs SSL inspection and Node.js rejects the intermediate certificate.
#
# Solution: Injects NODE_TLS_REJECT_UNAUTHORIZED=0 at all system levels
#   to ensure any user session inherits the variable.
#
# Usage: sudo bash Fix-NodeTLS.sh
#
# Where this script injects the variable:
#   1. /etc/environment            (PAM — login sessions, cron, systemd)
#   2. /etc/profile.d/node-tls.sh  (Login shells: bash, zsh)
#   3. ~/.bashrc of each user      (Interactive non-login shells)
#   4. ~/.profile of each user     (User login shells)
#   5. ~/.zshrc of each user       (If using zsh)
#
# Also fixes ownership of the ~/.gemini/ folder in case it was
# accidentally created as root (common cause of failure for normal users).
# =============================================================================

set -uo pipefail

# Minimum UID to consider as a human user
MIN_UID=1000
IGNORE_USERS=("nobody" "nfsnobody" "splunk")

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S %Z')

log_ok()   { echo -e "  ${GREEN}[OK]${NC} $1"; }
log_info() { echo -e "  ${CYAN}[INFO]${NC} $1"; }
log_fail() { echo -e "  ${RED}[FAILED]${NC} $1"; }
log_header() {
    echo ""
    echo -e "${BOLD}${CYAN}══════════════════════════════════════════════════════════════${NC}"
    echo -e "${BOLD}${CYAN}  $1${NC}"
    echo -e "${BOLD}${CYAN}══════════════════════════════════════════════════════════════${NC}"
}

# Function to inject a line into a file (idempotent)
inject_line() {
    local file="$1"
    local line="$2"
    local marker="$3"

    if [[ -f "$file" ]]; then
        if grep -q "$marker" "$file" 2>/dev/null; then
            # Already exists — replace to guarantee correct value
            sed -i "/${marker}/d" "$file"
        fi
    fi
    echo "$line" >> "$file"
}

is_ignored_user() {
    local user="$1"
    for ignored in "${IGNORE_USERS[@]}"; do
        [[ "$user" == "$ignored" ]] && return 0
    done
    return 1
}

# ==============================================================================
# Prerequisites Check
# ==============================================================================

if [[ $EUID -ne 0 ]]; then
    echo -e "${RED}ERROR: This script must be run as root (sudo).${NC}"
    exit 1
fi

log_header "FIX NODE TLS — $TIMESTAMP"
echo -e "  Hostname: ${BOLD}$(hostname)${NC}"

ERRORS=0

# ==============================================================================
# STEP 1: /etc/environment (PAM — all sessions)
# ==============================================================================

log_header "STEP 1: /etc/environment"

inject_line "/etc/environment" 'NODE_TLS_REJECT_UNAUTHORIZED=0' "NODE_TLS_REJECT_UNAUTHORIZED"
log_ok "NODE_TLS_REJECT_UNAUTHORIZED=0 defined in /etc/environment"

# Ensure NODE_USE_SYSTEM_CA is also there (belt and suspenders)
inject_line "/etc/environment" 'NODE_USE_SYSTEM_CA=true' "NODE_USE_SYSTEM_CA"
log_ok "NODE_USE_SYSTEM_CA=true defined in /etc/environment"

# ==============================================================================
# STEP 2: /etc/profile.d/ (Login shells)
# ==============================================================================

log_header "STEP 2: /etc/profile.d/node-tls.sh"

cat > /etc/profile.d/node-tls.sh << 'EOF'
# Node.js TLS — Fix for corporate network with SSL inspection
# Automatically generated by Fix-NodeTLS.sh
# DO NOT EDIT MANUALLY — will be overwritten on next execution
export NODE_TLS_REJECT_UNAUTHORIZED=0
export NODE_USE_SYSTEM_CA=true
EOF

chmod 644 /etc/profile.d/node-tls.sh
log_ok "Created /etc/profile.d/node-tls.sh"

# ==============================================================================
# STEP 3: Inject into user profiles + fix ownership
# ==============================================================================

log_header "STEP 3: User profiles"

# Phase 1: via getent passwd
while IFS=: read -r username _ uid _ _ homedir _; do
    # Filter system users
    [[ -z "$uid" || "$uid" -lt "$MIN_UID" ]] && continue
    is_ignored_user "$username" && continue
    [[ ! -d "$homedir" ]] && continue

    log_info "Processing user: ${BOLD}${username}${NC} (Home: $homedir)"

    # Inject in RC files
    for rcfile in ".bashrc" ".profile" ".zshrc"; do
        RCPATH="$homedir/$rcfile"
        if [[ -f "$RCPATH" ]]; then
            inject_line "$RCPATH" 'export NODE_TLS_REJECT_UNAUTHORIZED=0' "NODE_TLS_REJECT_UNAUTHORIZED"
            inject_line "$RCPATH" 'export NODE_USE_SYSTEM_CA=true' "NODE_USE_SYSTEM_CA"
            log_ok "$rcfile updated"
        fi
    done

    # ---- CRITICAL FIX: .gemini folder ownership ----
    # If someone ran "sudo gemini" or "sudo su" + "gemini" in the user's /home,
    # the .gemini folder might be owned by root, preventing the normal user
    # from reading/writing to it. This is a common cause of
    # "works as root but not as user".
    GEMINI_DIR="$homedir/.gemini"
    if [[ -d "$GEMINI_DIR" ]]; then
        CURRENT_OWNER=$(stat -c '%U' "$GEMINI_DIR" 2>/dev/null || echo "unknown")
        if [[ "$CURRENT_OWNER" != "$username" ]]; then
            log_info "⚠️  .gemini/ belongs to '$CURRENT_OWNER', fixing to '$username'..."
            chown -R "$username" "$GEMINI_DIR" 2>/dev/null
            if [[ $? -eq 0 ]]; then
                log_ok "Ownership of .gemini/ fixed to $username"
            else
                log_fail "Could not fix ownership of .gemini/"
                ((ERRORS++)) || true
            fi
        else
            log_ok ".gemini/ already belongs to $username"
        fi
    fi

done < <(getent passwd 2>/dev/null || cat /etc/passwd)

# Phase 2: Scan /home/ for Entra ID users that don't appear in getent
if [[ -d /home ]]; then
    for user_home in /home/*/; do
        [[ ! -d "$user_home" ]] && continue
        dir_username=$(basename "$user_home")

        # Skip if already processed via getent
        if getent passwd "$dir_username" &>/dev/null; then
            continue
        fi

        log_info "Processing (via /home/): ${BOLD}${dir_username}${NC}"

        for rcfile in ".bashrc" ".profile" ".zshrc"; do
            RCPATH="${user_home}${rcfile}"
            if [[ -f "$RCPATH" ]]; then
                inject_line "$RCPATH" 'export NODE_TLS_REJECT_UNAUTHORIZED=0' "NODE_TLS_REJECT_UNAUTHORIZED"
                inject_line "$RCPATH" 'export NODE_USE_SYSTEM_CA=true' "NODE_USE_SYSTEM_CA"
                log_ok "$rcfile updated"
            fi
        done

        # Fix ownership
        GEMINI_DIR="${user_home}.gemini"
        if [[ -d "$GEMINI_DIR" ]]; then
            OWNER_UID=$(stat -c '%u' "$user_home" 2>/dev/null)
            OWNER_GID=$(stat -c '%g' "$user_home" 2>/dev/null)
            if [[ -n "$OWNER_UID" ]]; then
                chown -R "${OWNER_UID}:${OWNER_GID}" "$GEMINI_DIR" 2>/dev/null
                log_ok "Ownership of .gemini/ fixed (UID:$OWNER_UID)"
            fi
        fi
    done
fi

# ==============================================================================
# SUMMARY
# ==============================================================================

log_header "SUMMARY"

echo ""
echo -e "  ${BOLD}Injected variables:${NC}"
echo -e "    NODE_TLS_REJECT_UNAUTHORIZED=0"
echo -e "    NODE_USE_SYSTEM_CA=true"
echo ""
echo -e "  ${BOLD}Locations:${NC}"
echo -e "    /etc/environment"
echo -e "    /etc/profile.d/node-tls.sh"
echo -e "    ~/.bashrc, ~/.profile, ~/.zshrc of each user"
echo ""

if [[ $ERRORS -eq 0 ]]; then
    echo -e "  ${GREEN}${BOLD}✓ COMPLETED SUCCESSFULLY${NC}"
else
    echo -e "  ${YELLOW}${BOLD}⚠ Completed with $ERRORS error(s) — check the log above${NC}"
fi

echo ""
echo -e "  ${YELLOW}IMPORTANT: The user must CLOSE their terminal and open a NEW one${NC}"
echo -e "  ${YELLOW}for the variables to take effect.${NC}"
echo ""
